// <auto-generated />
using System;
using LoginBase.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LoginBase.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210225042533_EstabilizarLlaves")]
    partial class EstabilizarLlaves
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LoginBase.Models.Empleado.EmpleadoColumna", b =>
                {
                    b.Property<int>("EmpleadoColumnaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmpleadoColumnaAnio")
                        .HasColumnType("int");

                    b.Property<int>("EmpleadoColumnaMes")
                        .HasColumnType("int");

                    b.Property<int>("SuaExcelId")
                        .HasColumnType("int");

                    b.HasKey("EmpleadoColumnaId");

                    b.HasIndex("SuaExcelId");

                    b.ToTable("EmpleadoColumnas");
                });

            modelBuilder.Entity("LoginBase.Models.Empleado.EmpleadoColumnaV", b =>
                {
                    b.Property<int>("EmpleadoColumnaVId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmpleadoColumnaId")
                        .HasColumnType("int");

                    b.Property<string>("EmpleadoColumnaValor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpleadoColumnaVId");

                    b.HasIndex("EmpleadoColumnaId");

                    b.ToTable("EmpleadoColumnaV");
                });

            modelBuilder.Entity("LoginBase.Models.Excel.ExcelColumna", b =>
                {
                    b.Property<int>("ExcelColumnaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ExcelColumnaNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExcelTipoId")
                        .HasColumnType("int");

                    b.HasKey("ExcelColumnaId");

                    b.HasIndex("ExcelTipoId");

                    b.ToTable("ExcelColumnas");
                });

            modelBuilder.Entity("LoginBase.Models.Excel.ExcelTipo", b =>
                {
                    b.Property<int>("ExcelTipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ExcelColumnaId")
                        .HasColumnType("int");

                    b.Property<string>("ExcelNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExcelTipoDescripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExcelTipoId");

                    b.ToTable("ExcelTipos");
                });

            modelBuilder.Entity("LoginBase.Models.Parametro", b =>
                {
                    b.Property<int>("ParametroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ParametroClave")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("ParametroDescripcion")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<bool?>("ParametroEstatusDelete")
                        .HasColumnType("bit");

                    b.Property<string>("ParametroNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ParametroValorFinal")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ParametroValorInicial")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ParametroId");

                    b.ToTable("Parametros");
                });

            modelBuilder.Entity("LoginBase.Models.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("RolEstatus")
                        .HasColumnType("bit");

                    b.Property<string>("RolNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RolId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("LoginBase.Models.Sua.ConfiguracionSua", b =>
                {
                    b.Property<int>("ConfiguracionSuaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ConfSuaEstatus")
                        .HasColumnType("bit");

                    b.Property<string>("ConfSuaNombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConfiguracionSuaId");

                    b.ToTable("ConfiguracionSuas");
                });

            modelBuilder.Entity("LoginBase.Models.Sua.ConfiguracionSuaNivel", b =>
                {
                    b.Property<int>("ConfiguracionSuaNivelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ConfSuaNNombre")
                        .HasColumnType("int");

                    b.Property<int>("ConfiguracionSuaId")
                        .HasColumnType("int");

                    b.HasKey("ConfiguracionSuaNivelId");

                    b.HasIndex("ConfiguracionSuaId");

                    b.ToTable("ConfiguracionSuaNiveles");
                });

            modelBuilder.Entity("LoginBase.Models.Sua.SuaExcel", b =>
                {
                    b.Property<int>("SuaExcelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ConfiguracionSuaNivelId")
                        .HasColumnType("int");

                    b.Property<int>("ExcelColumnaId")
                        .HasColumnType("int");

                    b.Property<int>("TipoPeriodoId")
                        .HasColumnType("int");

                    b.HasKey("SuaExcelId");

                    b.HasIndex("ConfiguracionSuaNivelId");

                    b.HasIndex("ExcelColumnaId");

                    b.ToTable("SuaExcels");
                });

            modelBuilder.Entity("LoginBase.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioApellidoM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioApellidoP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("UsuarioEstatusSesion")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UsuarioFechaLimite")
                        .HasColumnType("datetime2");

                    b.Property<string>("UsuarioNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioNumConfirmacion")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioToken")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("LoginBase.Models.Empleado.EmpleadoColumna", b =>
                {
                    b.HasOne("LoginBase.Models.Sua.SuaExcel", "SuaExcel")
                        .WithMany("EmpleadoColumna")
                        .HasForeignKey("SuaExcelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SuaExcel");
                });

            modelBuilder.Entity("LoginBase.Models.Empleado.EmpleadoColumnaV", b =>
                {
                    b.HasOne("LoginBase.Models.Empleado.EmpleadoColumna", "EmpleadoColumna")
                        .WithMany("EmpleadoColumnaV")
                        .HasForeignKey("EmpleadoColumnaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmpleadoColumna");
                });

            modelBuilder.Entity("LoginBase.Models.Excel.ExcelColumna", b =>
                {
                    b.HasOne("LoginBase.Models.Excel.ExcelTipo", null)
                        .WithMany("ExcelColumna")
                        .HasForeignKey("ExcelTipoId");
                });

            modelBuilder.Entity("LoginBase.Models.Sua.ConfiguracionSuaNivel", b =>
                {
                    b.HasOne("LoginBase.Models.Sua.ConfiguracionSua", "ConfiguracionSua")
                        .WithMany("ConfiguracionSuaNivel")
                        .HasForeignKey("ConfiguracionSuaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfiguracionSua");
                });

            modelBuilder.Entity("LoginBase.Models.Sua.SuaExcel", b =>
                {
                    b.HasOne("LoginBase.Models.Sua.ConfiguracionSuaNivel", "ConfiguracionSuaNivel")
                        .WithMany("SuaExcel")
                        .HasForeignKey("ConfiguracionSuaNivelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoginBase.Models.Excel.ExcelColumna", "ExcelColumna")
                        .WithMany("SuaExcel")
                        .HasForeignKey("ExcelColumnaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfiguracionSuaNivel");

                    b.Navigation("ExcelColumna");
                });

            modelBuilder.Entity("LoginBase.Models.Usuario", b =>
                {
                    b.HasOne("LoginBase.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("LoginBase.Models.Empleado.EmpleadoColumna", b =>
                {
                    b.Navigation("EmpleadoColumnaV");
                });

            modelBuilder.Entity("LoginBase.Models.Excel.ExcelColumna", b =>
                {
                    b.Navigation("SuaExcel");
                });

            modelBuilder.Entity("LoginBase.Models.Excel.ExcelTipo", b =>
                {
                    b.Navigation("ExcelColumna");
                });

            modelBuilder.Entity("LoginBase.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("LoginBase.Models.Sua.ConfiguracionSua", b =>
                {
                    b.Navigation("ConfiguracionSuaNivel");
                });

            modelBuilder.Entity("LoginBase.Models.Sua.ConfiguracionSuaNivel", b =>
                {
                    b.Navigation("SuaExcel");
                });

            modelBuilder.Entity("LoginBase.Models.Sua.SuaExcel", b =>
                {
                    b.Navigation("EmpleadoColumna");
                });
#pragma warning restore 612, 618
        }
    }
}
