// <auto-generated />
using System;
using LoginBase.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace tmf_group.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220414051310_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LoginBase.Models.Parametro", b =>
                {
                    b.Property<int>("ParametroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ParametroClave")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("ParametroDescripcion")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<bool?>("ParametroEstatusDelete")
                        .HasColumnType("bit");

                    b.Property<string>("ParametroNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ParametroValorFinal")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ParametroValorInicial")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ParametroId");

                    b.ToTable("Parametros");
                });

            modelBuilder.Entity("LoginBase.Models.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("RolEstatus")
                        .HasColumnType("bit");

                    b.Property<string>("RolNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RolId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("LoginBase.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmpleadoNoEmp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioApellidoM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioApellidoP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioClave")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("UsuarioEstatusSesion")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UsuarioFechaLimite")
                        .HasColumnType("datetime2");

                    b.Property<string>("UsuarioNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioNumConfirmacion")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioToken")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("tmf_group.Models.Empresa", b =>
                {
                    b.Property<int>("EmpresaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmpresaColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmpresaEstatus")
                        .HasColumnType("bit");

                    b.Property<string>("EmpresaLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpresaNombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpresaId");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("tmf_group.Models.PeriodoTipo", b =>
                {
                    b.Property<int>("PeriodoTipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PeriodoTipoNombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PeriodoTipoId");

                    b.ToTable("PeriodoTipos");
                });

            modelBuilder.Entity("tmf_group.Models.Recibo", b =>
                {
                    b.Property<string>("ReciboId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PeriodoTipoId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PeriodoTipoId1")
                        .HasColumnType("int");

                    b.Property<bool>("ReciboEstatus")
                        .HasColumnType("bit");

                    b.Property<string>("ReciboPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReciboPeriodoA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReciboPeriodoD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReciboPeriodoM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioNoEmp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReciboId");

                    b.HasIndex("PeriodoTipoId1");

                    b.ToTable("Recibos");
                });

            modelBuilder.Entity("LoginBase.Models.Usuario", b =>
                {
                    b.HasOne("tmf_group.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId");

                    b.HasOne("LoginBase.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId");

                    b.Navigation("Empresa");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("tmf_group.Models.Recibo", b =>
                {
                    b.HasOne("tmf_group.Models.PeriodoTipo", "PeriodoTipo")
                        .WithMany()
                        .HasForeignKey("PeriodoTipoId1");

                    b.Navigation("PeriodoTipo");
                });
#pragma warning restore 612, 618
        }
    }
}
